# Assembles modular SCL sources into a single TIA Portal import file.
param(
    [string]$OutputPath = (Join-Path $PSScriptRoot "..\build\Tankregelung_SCL_Quellen.scl")
)

$root = Join-Path $PSScriptRoot "..\src\tank"
$sources = @(
    "types\tank_mode.scl",
    "data_blocks\db_hmi_tank.scl",
    "scl\fb_tank_control.scl",
    "scl\fb_tank_sim.scl",
    "data_blocks\instance_dbs.scl",
    "plc\main.scl"
)

$outDir = Split-Path $OutputPath -Parent
if (-not (Test-Path $outDir)) {
    New-Item -ItemType Directory -Path $outDir -Force | Out-Null
}

$header = @(
    "// Tankregelung SCL - generated by build-scl.ps1"
    "// Do not edit directly; modify src/tank/*.scl and rebuild."
    ""
)

$content = [System.Collections.Generic.List[string]]::new()
foreach ($line in $header) { $content.Add($line) }

foreach ($relativePath in $sources) {
    $filePath = Join-Path $root $relativePath
    if (-not (Test-Path $filePath)) {
        throw "Missing source file: $filePath"
    }

    $content.Add("// --- $relativePath ---")
    $content.Add((Get-Content -Path $filePath -Raw).TrimEnd())
    $content.Add("")
}

Set-Content -Path $OutputPath -Value ($content -join [Environment]::NewLine) -Encoding UTF8
Write-Host "Built $($sources.Count) SCL modules -> $OutputPath"
